### ISSUE TITLE
using daisyui colors 

### ISSUE THREAD

**Issue by aymaneallaoui** [ZiGmaX809/tailwind-scrollbar-daisyui#2]
i just found about this amazing library but when i use it with daisyui colors it doesn't work 

```jsx
<ul tabIndex={0} className="dropdown-content z-[1] menu p-2 shadow bg-base-100 rounded-box w-52 max-h-48 overflow-y-scroll flex-nowrap overflow-hidden scrollbar-thin scrollbar-thumb-primary scrollbar-track-gray-200 ">
         {
          themes.map((theme) => (
          <li onClick={() => handleThemeChange(theme)}><a>{theme}</a></li>
          ))
          }
          
        </ul>
```
the scrollbar-thumb-primary seems not working  
![image](https://github.com/ZiGmaX809/tailwind-scrollbar-daisyui/assets/111997551/3f4a2aac-17e8-4256-8786-253e505863ba)

**Comment by ZiGmaX809** [comment]
tailwind-scrollbar has been updated and supports tailwind 3, please use tailwind-scrollbar, this repository will be removed.

https://github.com/adoxography/tailwind-scrollbar

**Comment by aymaneallaoui** [comment]
that for your work in this repo have a nice day
